const fs = require('fs');
const path = require('path');

function walk(dir, done) {
  let results = [];
  fs.readdir(dir, function(err, list) {
    if (err) return done(err);
    let pending = list.length;
    if (!pending) return done(null, results);
    list.forEach(function(file) {
      file = path.resolve(dir, file);
      fs.stat(file, function(err, stat) {
        if (stat && stat.isDirectory()) {
          walk(file, function(err, res) {
            results = results.concat(res);
            if (!--pending) done(null, results);
          });
        } else {
          if (file.endsWith('.tsx') || file.endsWith('.ts')) {
             results.push(file);
          }
          if (!--pending) done(null, results);
        }
      });
    });
  });
}

function processDirectory(dirToProcess) {
    walk(path.join(process.cwd(), dirToProcess, 'src'), (err, files) => {
        if (err) throw err;
        let updatedCount = 0;
        for (const file of files) {
          let content = fs.readFileSync(file, 'utf8');
          let original = content;
          
          // The massive nested string generated by patch2.js and patch.js
          const messyPattern = /\(\(\(process\.env\.NEXT_PUBLIC_API_URL.*?\)\.replace\(\/\\\/api\\\\\/.*?$/g;
          // Wait, let's use a simpler regex that targets the specific fetch calls
          
          // In customer:
          content = content.replace(/API = rawEnv\.replace\(\/\\\/api\\\/\?\$\/, ''\)\.replace\(\/\\\/\\+\$\/, ''\) \+ '\/api\/storefront';/g, "API = rawEnv.replace(/\\/api\\/?$/, '').replace(/\\/+$/, '') + '/api/storefront';\n    API = API.replace(/^http:\\/\\//i, 'https://');");
          
          // In vendor and admin:
          // The string is roughly `((process.env.NEXT_PUBLIC_API_URL && !process.env.NEXT_PUBLIC_API_URL.includes('localhost') ? process.env.NEXT_PUBLIC_API_URL : 'https://api.eghedev.com').replace(/\/api\/?$/, ''))`
          // Or even deeper nested.
          content = content.replace(/\(process\.env\.NEXT_PUBLIC_API_URL(?:\s*&&\s*!.*?)?\s*\?\s*.*?\s*:\s*'https:\/\/api\.eghedev\.com'\)(?:\.replace\(\/[^)]+\))*/g, 
            "(process.env.NEXT_PUBLIC_API_URL && !process.env.NEXT_PUBLIC_API_URL.includes('localhost') ? process.env.NEXT_PUBLIC_API_URL.replace(/:\\d+$/, '').replace(/^http:\\/\\//i, 'https://') : 'https://api.eghedev.com').replace(/\\/api\\/?$/, '')");
          
          if (content !== original) {
            fs.writeFileSync(file, content, 'utf8');
            updatedCount++;
            console.log(`Updated ${file}`);
          }
        }
        console.log(`Finished ${dirToProcess}, Total files updated: ${updatedCount}`);
      });
}

// Process Customer, Admin, Vendor
processDirectory('customer');
processDirectory('admin');
processDirectory('vendor');
